// apps/explorejsonplaceholder/src/app/nx-welcome.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-nx-welcome',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!--
     * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     This is a starter component and can be deleted.
     * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     Delete this file and get started with your project!
     * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     -->

    <div
      class="flex items-center justify-center w-full h-screen bg-slate-800 text-white"
    >
      <p class="text-3xl">Welcome to the Angular Front end</p>
    </div>
  `,
  styles: [],
  encapsulation: ViewEncapsulation.None,
})
export class NxWelcomeComponent {}

// apps/my-react-app/src/app/nx-welcome.tsx
export function NxWelcome({ title }: { title: string }) {
  return (
    <>
      <div className="bg-slate-800 text-white">
        <div className="px-2 flex items-center justify-center h-screen w-full">
          <div>
            <h1 className="text-3xl text-center">
              <span> Hello World </span>
            </h1>
            <p className="text-5xl">Welcome to {title}</p>
          </div>
        </div>
      </div>
    </>
  );
}

export default NxWelcome;
